menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/234129952
    GitHub: https://github.com/qq83387856
    Rss: /atom.xml

favicon: http://static.xiaomo.info/images/avatar.png
logo: http://static.xiaomo.info/images/avatar.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: xiaomo-dizi

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
